In [113]:
import numpy as np
import pandas as pd
from itertools import cycle

import matplotlib.pyplot as plt

nmers = 8

theta = np.arange(nmers)/float(nmers)*2*np.pi

r = np.array([1,0.3,
              1,0.3,
              1,0.3,
              1,0.3])

x = np.cos(theta) * r 
y = np.sin(theta) * r

plane = np.array(list(zip(x,y,np.zeros(len(x)))))
top = np.array([[0,0,1]]) 
bot = np.array([[0,0,-1]])

top_index = len(plane)
bot_index = len(plane)+1

# top range
top_seqs = list(zip(np.arange(len(plane)),
                    np.roll(np.arange(len(plane)),-1),
                    top_index * np.ones(len(plane)).astype(int)
                   ))

bot_seqs = list(zip(np.arange(len(plane)),
                    np.roll(np.arange(len(plane)),1),
                    bot_index * np.ones(len(plane)).astype(int)
                   ))

In [114]:
seqs = top_seqs + bot_seqs

In [115]:
locs = [list(plane) + list(top) + list(bot)][0]

In [116]:
locs

[array([1., 0., 0.]),
 array([0.21213203, 0.21213203, 0.        ]),
 array([6.123234e-17, 1.000000e+00, 0.000000e+00]),
 array([-0.21213203,  0.21213203,  0.        ]),
 array([-1.0000000e+00,  1.2246468e-16,  0.0000000e+00]),
 array([-0.21213203, -0.21213203,  0.        ]),
 array([-1.8369702e-16, -1.0000000e+00,  0.0000000e+00]),
 array([ 0.21213203, -0.21213203,  0.        ]),
 array([0, 0, 1]),
 array([ 0,  0, -1])]

In [117]:
def write_ply_file(locs, seqs, outfile):
    with open(outfile,'w+') as f:
        f.write('ply\nformat ascii 1.0\nelement vertex %s\nproperty float x\nproperty float y\nproperty float z\nelement face %s\nproperty list uint uint vertex_index\nend_header\n'%(len(locs),len(seqs),))
        for i in locs:
            f.write('%s %s %s\n'%(i[0],i[1],i[2]))
        for i in seqs:
            f.write('%s %s %s %s\n'%(len(i),i[0],i[1],i[2]))

In [118]:
write_ply_file(locs,seqs,'outfile.ply')

In [119]:
import plyfile

In [120]:
plyfile.PlyData.read('./outfile.ply')

PlyData((PlyElement('vertex', (PlyProperty('x', 'float'), PlyProperty('y', 'float'), PlyProperty('z', 'float')), count=10, comments=[]), PlyElement('face', (PlyListProperty('vertex_index', 'uint', 'uint'),), count=16, comments=[])), text=True, byte_order='=', comments=[], obj_info=[])

In [121]:
dir(plyfile)

['PlyData',
 'PlyElement',
 'PlyElementParseError',
 'PlyHeaderParseError',
 'PlyListProperty',
 'PlyParseError',
 'PlyProperty',
 '_PlyHeaderParser',
 '__builtins__',
 '__cached__',
 '__doc__',
 '__file__',
 '__loader__',
 '__name__',
 '__package__',
 '__spec__',
 '_a',
 '_b',
 '_byte_order_map',
 '_byte_order_reverse',
 '_byteorder',
 '_can_mmap',
 '_check_comments',
 '_check_name',
 '_data_type_relation',
 '_data_type_reverse',
 '_data_types',
 '_islice',
 '_lookup_type',
 '_native_byte_order',
 '_np',
 '_open_stream',
 '_range',
 '_read_array',
 '_types_list',
 '_types_set',
 '_write_array',
 'make2d']

In [ ]:
#bottom range